[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --no-input"]

[start]
cmd = "gunicorn config.wsgi:application --workers 2 --threads 4 --bind 0.0.0.0:$PORT --log-level info"
