[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi:application --workers 2 --threads 4 --bind 0.0.0.0:$PORT --log-level info"
healthcheckPath = "/mehlr/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
